name: okhttp
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

dependencies:
  async: ^2.11.0
  http_parser: ^4.0.2
  nice_dart:
    git:
      url: https://github.com/Noobware1/nice_dart.git
      ref: master
  socks5_proxy: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
